package com.project.pojo;
// default package
// Generated Jan 14, 2017 12:09:05 AM by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipment generated by hbm2java
 */
@Entity
@Table(name = "equipment", catalog = "minirisdb")
public class Equipment implements java.io.Serializable {

	private Integer idequipment;
	private String modality;
	private String aeTitle;
	private Set<Study> studies = new HashSet<Study>(0);

	public Equipment() {
	}

	public Equipment(String modality, String aeTitle, Set studies) {
		this.modality = modality;
		this.aeTitle = aeTitle;
		this.studies = studies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idequipment", unique = true, nullable = false)
	public Integer getIdequipment() {
		return this.idequipment;
	}

	public void setIdequipment(Integer idequipment) {
		this.idequipment = idequipment;
	}

	@Column(name = "modality", length = 3)
	public String getModality() {
		return this.modality;
	}

	public void setModality(String modality) {
		this.modality = modality;
	}

	@Column(name = "ae_title", length = 50)
	public String getAeTitle() {
		return this.aeTitle;
	}

	public void setAeTitle(String aeTitle) {
		this.aeTitle = aeTitle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipment")
	public Set<Study> getStudies() {
		return this.studies;
	}

	public void setStudies(Set studies) {
		this.studies = studies;
	}

}
